---
title: "Detailled presentation of the data"
lang: en-US
format:
  html:
    number-sections: true
    page-layout: full

---


# General presentation of the data

Data prepared for this project gathers all of the housing transactions in France between 2014 and 2021 and details about the property sold.
Because the characteristics of the property sold isn't open source, the data you'll be working with are **synthetic data**. It has been generated to mirror the original data.

If you want to have a closer look at the data, CEREMA publishes on [its website](%5D(https://doc-datafoncier.cerema.fr/doc/ff/pb0010_local)) an extensive documentation of the different datasets, the variables, their modalities and the overall quality of variable.

## List of variable and explanations

{{< include "temp/table_dict.qmd" >}}

See [CEREMA's documentation (in French)](https://doc-datafoncier.cerema.fr/doc/ff/pb0010_local) for a more detailled description.

Note that the variable year of the building has been harmonized to correct for typing mistakes. Here are the transformation made from the original data :

| Original modality | Corrections to original modality | Exemple of transformation |
|------------------------|------------------------|------------------------|
| 1 ≤ prop_year ≤ 22 | Add 2000 as the first digits were not entered | 8 → 2008 |
| 23 ≤ prop_year ≤ 99 | Add 1900 as the first digits were not entered | 83 → 1983 |
| 100 ≤ prop_year ≤ 119 | Set to 0 as it is unknown | 105 → 0 |
| 120 ≤ prop_year ≤ 200 | Add a 0 at the end as the last digit has not been entered | 187 → 1870 |
| 201 ≤ prop_year ≤ 299 | Set to 0 as it is unknown | 250 → 0 |
| 300 ≤ prop_year ≤ 999 | Add 1000 as the first digits have not been entered | 980 → 1980 |
| 1000 ≤ prop_year ≤ 1120 | Set to 0 as it is unknown | 1005 → 0 |
| 1120 ≤ prop_year ≤ 1199 | Replace the second 1 with 9 | 1155 → 1955 |
| 1200 ≤ prop_year ≤ 2022 | No change | 1200 → 1200 |

More information about this transformation is available [online](https://doc-datafoncier.cerema.fr/doc/ff/pb40_pevprincipale/prop_year_harm) (in French).
