name: Publish site

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  publish-site:
      runs-on: ubuntu-latest

      permissions:
        contents: write
      steps:

        - name: Check out repository
          uses: actions/checkout@v5

        - name: Install the latest version of uv
          uses: astral-sh/setup-uv@v6
          with:
            version: "latest"
            python-version: 3.13

        - name: Set up Quarto
          uses: quarto-dev/quarto-actions/setup@v2

        # - name: Generate model  # wont work as missing S3 env vars
        #   run: |
        #     uv run temp/generate_models.py 
        #     mc cp final_gb_model.joblib s3/projet-funathon/2026/project1/models/final_gb_model.joblib
        #     mc cp final_rf_model.joblib s3/projet-funathon/2026/project1/models/final_rf_model.joblib

        - name: Render
          run: uv run quarto render

        - name: Publish to GitHub Pages
          uses: quarto-dev/quarto-actions/publish@v2
          with:
            target: gh-pages
            render: false
